### ISSUE TITLE
Transfer to fanuc-oss organisation?

### ISSUE THREAD

**Issue by gavanderhoorn** [gavanderhoorn/rossum#30]
Something to consider: create an onofficial "Fanuc Open-Source Software" GH organisation and transfer this repository to that organisation, together with `ktransw_pi` and potentially other Fanuc-specific open-source tools to focus efforts and improved visibility of related projects.

Opening this here to check whether this is something that other Fanuc OSS tool maintainers/developers would be interested in.

**Comment by gavanderhoorn** [comment]
@kobbled, @unreal: opinions / comments?

**Comment by gavanderhoorn** [comment]
@unreal: I'm specifically curious to know whether you'd be interested in hosting your (awesome) tools like `tp_plus`, `go-fanuc`, `KUnit`, `vim-tp` and others in such an org, or whether you'd rather keep them on the OneRobotics org.

Right now I have the impression that there are probably quite a few Fanuc-focused OSS projects on GH, but living on personal accounts they are hard to find. Hosting them in a single organisation improves their chances of being found *and* chances of related / companion projects being found.

**Comment by unreal** [comment]
I agree it's probably hard to find some of these projects, though I think GitHub's tagging feature (e.g. [#fanuc][3]) helps.

Perhaps a better solution with less overhead is a curated list of projects e.g. [Awsome Vue.js][1], [Awesome Go][2], etc.

[1]: https://github.com/vuejs/awesome-vue
[2]: https://github.com/avelino/awesome-go
[3]: https://github.com/topics/fanuc

**Comment by gavanderhoorn** [comment]
Awesome lists are nice, but the trouble with them would be that they would have to be maintained by someone.

Hosting related projects in a single org does that sort of automatically.

The tagging certainly helps.

**Comment by kobbled** [comment]
Currently I am just checking the fanuc topic for new projects like @unreal suggested. An org might be a good idea as it might incentivize sharing and open sourcing from a community that isn't accustom to these practices. However, that's more of a philosophical debate on the typical fanuc integrator/developer.

**Comment by kobbled** [comment]
@gavanderhoorn, would you include ros-industrial fanuc related projects under this banner,or is that outside of this scope?

**Comment by gavanderhoorn** [comment]
@kobbled wrote:
> An org might be a good idea as it might incentivize sharing and open sourcing from a community that isn't accustom to these practices.

yes, that was my thinking as well.

> would you include ros-industrial fanuc related projects under this banner,or is that outside of this scope?

I'm not sure, because those packages are not "stand-alone" but allow ROS to integrate/communicate with Fanuc robots. Outside of the ROS context they are not really useful (or usable even).

The tools/utilities/scripts/etc I'm thinking of would be purely Fanuc-specific and not tied to any framework or platform specifically.

Things like [iBaff/vscode-fanuc-karel](https://github.com/iBaff/vscode-fanuc-karel) and [alek5k/TPSyntaxHighlighter](https://github.com/alek5k/TPSyntaxHighlighter) would fall into this category. As do all my Fanuc related projects (apart from the ROS-I related ones).

**Comment by gavanderhoorn** [comment]
Inviting @iBaff and @alek5k to the discussion.

**Comment by kobbled** [comment]
I'm mainly thinking about post-processors. People probably don't use Victor Lamoine's fanuc post processor outside of ros context, but you definitely can.

**Comment by gavanderhoorn** [comment]
It's not really a post-processor imo, but I get your point.

(btw: there is a whole bunch of post-processors over at [ros-industrial/robodk_postprocessors](https://github.com/ros-industrial/robodk_postprocessors))

**Comment by gavanderhoorn** [comment]
@VictorLamoine: opinion?

**Comment by gavanderhoorn** [comment]
Note btw that moving to an org instead of separate user accounts does not imply any loss of control or handing repositories "over" to me or anyone else. All authors would remain in full control of the work of course.

And I also feel there would still be plenty of opportunity to do any branding as desired.

**Comment by VictorLamoine** [comment]
The only solution that is able to aggregate from multiple websites (GitHub, GitLab etc.) is an "Awesome" like list.

Creating an organization will only let you list a GitHub repos. I would go for an "Awesome" list.

**Comment by gavanderhoorn** [comment]
> Creating an organization will only let you list a GitHub repos.

True.

> I would go for an "Awesome" list.

That would require maintenance, as I wrote in https://github.com/gavanderhoorn/rossum/issues/30#issuecomment-485878880.

**Comment by gavanderhoorn** [comment]
Thanks for all your input. I'm going to close this issue, as I was merely curious to see whether there would be enough momentum to come together and form some sort of community around the idea of OSS for Fanuc robots and related applications.

It seems there is something, but maintaining a list/index/overview requires both additional effort and would introduce yet another repository on a personal account.

Perhaps someone else is motivated enough to start an Awesome Fanuc OSS list. In that case, they're more than welcome to put any of my repositories on it :).

**Comment by VictorLamoine** [comment]
@gavanderhoorn I've got more than enough to deal with so I'll pass :smile: 

I'll add `fanuc` tags to my repositories, this will improve visibility.
